---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 6
DeathKnightSpells = {

}

BloodSpells = {

}

FrostSpells = {

}

UnholySpells = {

}

DeathKnightPVPSpells = {

}

DeathKnightLegendary = {
}

function insertDeathKnightConfig(configRoot)
    local _,Blood,_,BloodIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Frost,_,FrostIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Unholy,_,UnholyIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        DeathKnight = {
            order = 1,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", "Interface\\ICONS\\Classicon_deathKnight", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Blood = {
            order = 2,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", BloodIcon, Blood) end,
            args = {
            }
        },
        Frost = {
            order = 3,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", FrostIcon, Frost) end,
            args = {
            }
        },
        Unholy = {
            order = 4,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", UnholyIcon, Unholy) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end