---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 6
DeathKnightSpells = {
    48792,      --冰固堅韌
    3714,       --冰霜之徑
    145629,     --反魔法力場
    48265,      --死神逼近
    48743,      --死亡契約
    212552,     --闇境靈行
}

BloodSpells = {
    49039,      --巫妖之軀
    55233,      --血族之裔
    195181,     --骸骨之盾
    81256,      --符文武器幻舞
    48707,      --反魔法護罩
    194679,     --符文轉化
    273947,     --凝血作用
    194844,     --骸骨風暴
    219809,     --墓碑
}

DeathKnightFrostSpells = {
    47568,      --強力符文武器
    51271,      --冰霜之柱
    59052,      --凝霜
    51124,      --殺戮酷刑
    253595,     --無情之擊
    194879,     --冰結之爪
    281209,     --冰冷之心
    321995,     --寒凍血脈
}

UnholySpells = {
    207289,     --穢邪之擊
    115989,     --穢邪荒疫
}

DeathKnightPVPSpells = {
    233411,     --血債血償
    288977,     --注入
    228579,     --擰心光環
    228581,     --腐朽光環
    228583,     --亡域光環
}

DeathKnightLegendary = {
}

function insertDeathKnightConfig(configRoot)
    local _,Blood,_,BloodIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Frost,_,FrostIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Unholy,_,UnholyIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        DeathKnight = {
            order = 1,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", "Interface\\ICONS\\Classicon_deathKnight", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Blood = {
            order = 2,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", BloodIcon, Blood) end,
            args = {
            }
        },
        Frost = {
            order = 3,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", FrostIcon, Frost) end,
            args = {
            }
        },
        Unholy = {
            order = 4,
            type = "group",
            name = function() return format("|cffC41F3B|T%s:16|t %s", UnholyIcon, Unholy) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end