---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:47
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 12
DemonHunterSpells = {
    258920,     --獻祭光環
    188501,     --靈視
}

HavocSpells = {
    162264,     --惡魔化身
    212800,     --殘影
    209426,     --黑暗
    347462,     --無縛混沌
    196555,     --虛空穿越
    208628,     --氣勢如虹
	427641,		--慣性
}

VengeanceSpells = {
    187827,     --惡魔化身
    203981,     --靈魂碎片
    203819,     --惡魔尖刺
    326863,     --破滅壁壘
    263648,     --靈魂屏障
}

DemonHunterPVPSpells = {
    206804,     --從天而降
    205629,     --惡魔踐踏
    208769,     --永恆狩獵
    208796,     --鋸齒尖刺
}

DemonHunterLegendary = {
}

function insertDemonHunterConfig(configRoot)
    local _,Havoc,_,HavocIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Vengeance,_,VengeanceIcon = GetSpecializationInfoForClassID(ClassID, 2)

    configRoot.args.BuffOption.args = {
        DemonHunter = {
            order = 1,
            type = "group",
            name = function() return format("|cffA330C9|T%s:16|t %s", "Interface\\ICONS\\Classicon_demonHunter", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Havoc = {
            order = 2,
            type = "group",
            name = function() return format("|cffA330C9|T%s:16|t %s", HavocIcon, Havoc) end,
            args = {
            }
        },
        Vengeance = {
            order = 3,
            type = "group",
            name = function() return format("|cffA330C9|T%s:16|t %s", VengeanceIcon, Vengeance) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end