---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:47
---


local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 11
DruidSpells = {

}

BalanceSpells = {

}

FeralSpells = {

}

RestorationSpells = {

}

GuardianSpells = {

}

DruidPVPSpells = {

}

DruidLegendary = {
}

function insertDruidConfig(configRoot)
    local _,Balance,_,BalanceIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Feral,_,FeralIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Guardian,_,GuardianIcon = GetSpecializationInfoForClassID(ClassID, 3)
    local _,Restoration,_,RestorationIcon = GetSpecializationInfoForClassID(ClassID, 4)


    configRoot.args.BuffOption.args = {
        Druid = {
            order = 1,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", "Interface\\ICONS\\Classicon_Druid", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Balance = {
            order = 2,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", BalanceIcon, Balance) end,
            args = {
            }
        },
        Feral = {
            order = 3,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", FeralIcon, Feral) end,
            args = {
            }
        },
        Guardian = {
            order = 4,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", GuardianIcon, Guardian) end,
            args = {
            }
        },
        Restoration = {
            order = 5,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", RestorationIcon, Restoration) end,
            args = {
            }
        },
        PVP = {
            order = 6,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 8,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end