---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:47
---


local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 11
DruidSpells = {
    61336,      --求生本能
    192081,     --鋼鐵毛皮
    106898,     --奔竄咆哮
    22812,      --樹皮術
    1850,       --突進
    252216,     --虎豹突進
    8936,       --癒合

}

BalanceSpells = {
    194223,     --星芎連線
    48517,      --日蝕
    48518,      --月蝕
    191034,     --星殞術
    279709,     --星爵
}

FeralSpells = {
    106951,     --狂暴
    5217,       --猛虎之怒
    135700,     --節能施法
    69369,      --猛獸迅捷
    102543,     --化身:叢林之王
    52610,      --凶蠻咆哮
}

GuardianSpells = {
    22842,      --狂暴恢復
    50334,      --凶暴
    93622,      --浴血奮戰
    77761,      --奔竄咆哮
    155835,     --針刺毛皮
    102558,     --化身:厄索克守護者
    108294,     --野性之心
}

DruidRestorationSpells = {
    102342,     --鐵樹皮術
    33763,      --生命之花
    774,        --回春術
    16870,      --節能施法
    48438,      --野性痊癒
    102351,     --塞納里奧結界
    108292,     --野性之心
}

DruidPVPSpells = {

}

DruidLegendary = {
}

function insertDruidConfig(configRoot)
    local _,Balance,_,BalanceIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Feral,_,FeralIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Guardian,_,GuardianIcon = GetSpecializationInfoForClassID(ClassID, 3)
    local _,Restoration,_,RestorationIcon = GetSpecializationInfoForClassID(ClassID, 4)


    configRoot.args.BuffOption.args = {
        Druid = {
            order = 1,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", "Interface\\ICONS\\Classicon_Druid", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Balance = {
            order = 2,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", BalanceIcon, Balance) end,
            args = {
            }
        },
        Feral = {
            order = 3,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", FeralIcon, Feral) end,
            args = {
            }
        },
        Guardian = {
            order = 4,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", GuardianIcon, Guardian) end,
            args = {
            }
        },
        Restoration = {
            order = 5,
            type = "group",
            name = function() return format("|cffFF7D0A|T%s:16|t %s", RestorationIcon, Restoration) end,
            args = {
            }
        },
        PVP = {
            order = 6,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 7,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 8,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end