---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 8
MageSpells = {
    45438,      --寒冰屏障
    116014,     --力之符文
    116267,     --咒法之流
    342246,     --時光倒轉
    235450,     --稜彩屏障
    235313,     --炙炎屏障
    11426,      --寒冰護體
    130,        --緩落術
}

ArcaneSpells = {
    12042,      --祕法強化
    12051,      --喚醒
    205025,     --氣定神閒
    263725,     --節能施法
    110960,     --強效隱形
    264774,     --以三為多
    210126,     --祕法魔寵
    321388,     --心智開通

}

FireSpells = {
    190319,     --燃灼
    48107,      --升溫
    48108,      --焦炎之痕
}

MageFrostSpells = {
    12472,      --冰寒脈動
    44544,      --冰霜之指
    190446,     --腦部凍結
    205473,     --冰柱
    205766,     --冰寒徹骨

}

MagePVPSpells = {
    198158,     --群體隱形術
    198111,     --時光護盾
    198065,     --稜彩披風
    203277,     --烈焰火種
    203285,     --烈焰火炮
    198144,     --寒冰形體
}

MageLegendary = {
}

function insertMageConfig(configRoot)
    local _,Arcane,_,ArcaneIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Fire,_,FireIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Frost,_,FrostIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Mage = {
            order = 1,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", "Interface\\ICONS\\Classicon_Mage", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Arcane = {
            order = 2,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", ArcaneIcon, Arcane) end,
            args = {
            }
        },
        Fire = {
            order = 3,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", FireIcon, Fire) end,
            args = {
            }
        },
        Frost = {
            order = 4,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", FrostIcon, Frost) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end