---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 8
MageSpells = {

}

ArcaneSpells = {

}

FireSpells = {

}

FrostSpells = {

}

MagePVPSpells = {

}

MageLegendary = {
}

function insertMageConfig(configRoot)
    local _,Arcane,_,ArcaneIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Fire,_,FireIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Frost,_,FrostIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Mage = {
            order = 1,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", "Interface\\ICONS\\Classicon_Mage", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Arcane = {
            order = 2,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", ArcaneIcon, Arcane) end,
            args = {
            }
        },
        Fire = {
            order = 3,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", FireIcon, Fire) end,
            args = {
            }
        },
        Frost = {
            order = 4,
            type = "group",
            name = function() return format("|cff69CCF0|T%s:16|t %s", FrostIcon, Frost) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end