---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:47
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 10
MonkSpells = {

    120954,     --石形絕釀
    243435,     --石形絕釀
    116841,     --猛虎出閘
    119085,     --真氣飛龍穿
    116847,     --飛玉疾風
    122278,     --卸勁訣
    122783,     --去魔訣
    101643,     --超凡入聖
}

BrewmasterSpells = {
    322507,     --天尊絕釀
    115176,     --冥思禪功
    325092,     --純淨真氣
    132578,     --招喚玄牛怒兆
}

MistweaverSpells = {
    116849,     --氣繭護體
    116680,     --聚雷茶
    124682,     --迷霧繚繞
    119611,     --回升迷霧
    191840,     --精華之泉
    196725,     --翠玉清風
    202090,     --僧院教義
}

WindwalkerSpells = {
    137639,     --風火大地
    152173,     --冰心訣
    125174,     --乾坤挪移
    196741,     --連珠狂拳
}

MonkPVPSpells = {
    202335,     --雙酒罈
    209584,     --聚禪茶
    227344,     --回春迷霧
    287504,     --虎群領袖
    201447,     --乘風而行
}

MonkLegendary = {
}

function insertMonkConfig(configRoot)
    local _,Brewmaster,_,BrewmasterIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Mistweaver,_,MistweaverIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Windwalker,_,WindwalkerIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Monk = {
            order = 1,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", "Interface\\ICONS\\Classicon_Monk", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Brewmaster = {
            order = 2,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", BrewmasterIcon, Brewmaster) end,
            args = {
            }
        },
        Mistweaver = {
            order = 3,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", MistweaverIcon, Mistweaver) end,
            args = {
            }
        },
        Windwalker = {
            order = 4,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", WindwalkerIcon, Windwalker) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end