---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:47
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 10
MonkSpells = {

}

BrewmasterSpells = {

}

MistweaverSpells = {

}

WindwalkerSpells = {

}

MonkPVPSpells = {

}

MonkLegendary = {
}

function insertMonkConfig(configRoot)
    local _,Brewmaster,_,BrewmasterIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Mistweaver,_,MistweaverIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Windwalker,_,WindwalkerIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Monk = {
            order = 1,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", "Interface\\ICONS\\Classicon_Monk", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Brewmaster = {
            order = 2,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", BrewmasterIcon, Brewmaster) end,
            args = {
            }
        },
        Mistweaver = {
            order = 3,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", MistweaverIcon, Mistweaver) end,
            args = {
            }
        },
        Windwalker = {
            order = 4,
            type = "group",
            name = function() return format("|cff00FF96|T%s:16|t %s", WindwalkerIcon, Windwalker) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end