---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---


local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 2
PaladinSpells = {

}

HolySpells = {

}

ProtectionSpells = {

}

RetributionSpells = {

}

PaladinPVPSpells = {

}

PaladinLegendary = {
}

function insertPaladinConfig(configRoot)
    local _,Holy,_,HolyIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Protection,_,ProtectionIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Retribution,_,RetributionIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Paladin = {
            order = 1,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", "Interface\\ICONS\\Classicon_Paladin", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Holy = {
            order = 2,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", HolyIcon, Holy) end,
            args = {
            }
        },
        Protection = {
            order = 3,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", ProtectionIcon, Protection) end,
            args = {
            }
        },
        Retribution = {
            order = 4,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", RetributionIcon, Retribution) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end