---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---


local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 2
PaladinSpells = {
    31884,      --復仇之怒
    642,        --聖盾術
    132403,     --公正之盾
    223819,     --神聖意圖
    105809,     --神聖復仇者
    --152262,     --六翼天使
    1022,       --保護祝福
    1044,       --自由祝福
    32223,      --十字軍光環
    465,        --虔誠光環
    183435,     --懲戒光環
}

PaladinHolySpells = {
    31821,      --精通光環
    54149,      --聖光灌注
    498,        --聖佑術
    214202,     --依法而治
    216331,     --復仇十字軍
}

PaladinProtectionSpells = {
    86659,      --遠古諸王守護者
    31850,      --忠誠防衛者
    280373,     --盾牌壁壘
    204018,     --抗咒祝福
}

RetributionSpells = {
    231895,     --十字軍
    184662,     --復仇聖盾
    209785,     --正義怒火
    269571,     --狂熱
}

PaladinPVPSpells = {
    210391,     --黎明前的黑暗


}

PaladinLegendary = {
}

function insertPaladinConfig(configRoot)
    local _,Holy,_,HolyIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Protection,_,ProtectionIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Retribution,_,RetributionIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Paladin = {
            order = 1,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", "Interface\\ICONS\\Classicon_Paladin", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Holy = {
            order = 2,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", HolyIcon, Holy) end,
            args = {
            }
        },
        Protection = {
            order = 3,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", ProtectionIcon, Protection) end,
            args = {
            }
        },
        Retribution = {
            order = 4,
            type = "group",
            name = function() return format("|cffF58CBA|T%s:16|t %s", RetributionIcon, Retribution) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end