---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 5
PriestSpells = {
    19236,      --絕望禱言
    17,         --真言術盾
    586,        --漸隱術
    111759,     --飄浮術
}

DisciplineSpells = {
    81782,      --真言術壁
    33206,      --痛苦鎮壓
    47536,      --狂喜
}

PriestHolySpells = {
    215769,     --救贖之靈
    64844,      --神聖禮頌
    64843,      --神聖禮頌
    200183,     --神化
    121557,     --天使之羽
    47788,      --守護聖靈
    41635,      --癒合禱言
    321379,     --祈禱法陣
    114255,     --光之澎拜
    77489,      --光明迴響
    139,        --恢復
}

ShadowSpells = {
    194249,     --虛無型態
    319952,     --獻身瘋狂
    47585,      --影散
    15286,      --吸血鬼的擁抱
}

PriestPVPSpells = {
    213602,     --強效漸隱術
    197862,     --大天使
    197871,     --黑暗大天使
    213610,     --神聖結界
    289655,     --聖言術專注
    329543,     --神性晉升
    232707,     --希望曙光
    247776,     --心靈創傷
}

PriestLegendary = {
    336267,     --快速專注
}


function insertPriestConfig(configRoot)
    local _,Discipline,_,DisciplineIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Holy,_,HolyIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Shadow,_,ShadowIcon = GetSpecializationInfoForClassID(ClassID, 3)
    configRoot.args.BuffOption.args = {
        Priest = {
            order = 1,
            type = "group",
            name = function() return format("|cffFFFFFF|T%s:16|t %s", "Interface\\ICONS\\Classicon_priest", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Discipline = {
            order = 2,
            type = "group",
            name = function() return format("|cffFFFFFF|T%s:16|t %s", DisciplineIcon, Discipline) end,
            args = {
            }
        },
        Holy = {
            order = 3,
            type = "group",
            name = function() return format("|cffFFFFFF|T%s:16|t %s", HolyIcon, Holy) end,
            args = {
            }
        },
        Shadow = {
            order = 4,
            type = "group",
            name = function() return format("|cffFFFFFF|T%s:16|t %s", ShadowIcon, Shadow) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary = {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end