---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 4
RogueSpells = {

}

AssassinationSpells = {

}

OutlawSpells = {

}

SubtletySpells = {

}

RoguePVPSpells = {

}

RogueLegendary = {
}

function insertRogueConfig(configRoot)
    local _,Assassination,_,AssassinationIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Outlaw,_,OutlawIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Subtlety,_,SubtletyIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Rogue = {
            order = 1,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", "Interface\\ICONS\\Classicon_rogue", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Assassination = {
            order = 2,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", AssassinationIcon, Assassination) end,
            args = {
            }
        },
        Outlaw = {
            order = 3,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", OutlawIcon, Outlaw) end,
            args = {
            }
        },
        Subtlety = {
            order = 4,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", SubtletyIcon, Subtlety) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end