---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 4
RogueSpells = {
    1784,       --潛行
    315496,     --切割
    185311,     --赤紅藥瓶
    31224,      --暗影披風
    5277,       --閃避
    11327,      --消失
    1966,       --佯攻
    2983,       --疾跑
    114018,     --隱蔽護罩
    193538,     --矯捷
    2823,       --致命毒藥
    3408,       --致殘毒藥
    8679,       --致傷毒藥
    315584,     --速效毒藥
}

AssassinationSpells = {
    193641,     --精密計畫
    256735,     --刺客大師
    108211,     --吸血毒藥
}

OutlawSpells = {
    13750,      --能量刺激
    13877,      --劍刃亂舞
    199600,     --地底藏寶
    193357,     --無情精準
    193356,     --舷砲齊射
    193358,     --大亂鬥
    193359,     --絕對方位
    199603,     --骷髏旗
    195627,     --大好機會
}

SubtletySpells = {
    121471,     --暗影之刃
    185422,     --暗影之舞
    212283,     --死亡徵兆
}

RoguePVPSpells = {
    198368,     --見者有分
    213981,     --冷血
}

RogueLegendary = {
    340094,     --刺客大師印記
}

function insertRogueConfig(configRoot)
    local _,Assassination,_,AssassinationIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Outlaw,_,OutlawIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Subtlety,_,SubtletyIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Rogue = {
            order = 1,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", "Interface\\ICONS\\Classicon_rogue", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Assassination = {
            order = 2,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", AssassinationIcon, Assassination) end,
            args = {
            }
        },
        Outlaw = {
            order = 3,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", OutlawIcon, Outlaw) end,
            args = {
            }
        },
        Subtlety = {
            order = 4,
            type = "group",
            name = function() return format("|cffFFF569|T%s:16|t %s", SubtletyIcon, Subtlety) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end