---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 7
ShamanSpells = {
    114050,     --卓越術
    108271,     --星界轉移
    79206,      --靈行者之賜
    2645,       --鬼魂之狼
    260881,     --幽靈狼
    192082,     --風驟圖騰
    546,        --水上行走
    192106,     --閃電盾
    974,        --大地之盾
    52127,      --水之盾
}

ElementalSpells = {
    77762,      --熔岩奔騰
    285514,     --奔騰能量
    272737,     --無限能量
    260734,     --元素大師
    108281,     --先祖導引
}

EnhancementSpells = {
    344179,     --氣漩武器
    224125,     --熔火狼
    224126,     --冰霜狼
    224127,     --閃電狼
    333957,     --野性之魂
    198300,     --風暴匯聚
    201846,     --風暴使者
    187878,     --風暴轟擊
    320137,     --風暴守護者
    58875,      --幽魂步伐
    327942,     --風怒圖騰

}

ShamanRestorationSpells = {
    325174,     --靈魂連結圖騰
    73920,      --治療之雨
    320763,     --法力之潮
    61295,      --激流
    201633,     --大地盾牆圖騰
    157504,     --雲爆圖騰
    207400,     --先祖活力
    53390,      --治療之潮
    280615,     --暴洪
}

ShamanPVPSpells = {
    204366,     --雷霆充能
    210918,     --靈體型態
    208963,     --天怒圖騰
    204262,     --幽魂回復
    8178,       --根基圖騰
    236502,     --浪潮使者
    290241,     --先祖之賜
    --204293,     --靈魂連結
}

ShamanLegendary = {
}

function insertShamanConfig(configRoot)
    local _,Elemental,_,ElementalIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Enhancement,_,EnhancementIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Restoration,_,RestorationIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Shaman = {
            order = 1,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", "Interface\\ICONS\\Classicon_Shaman", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Elemental = {
            order = 2,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", ElementalIcon, Elemental) end,
            args = {
            }
        },
        Enhancement = {
            order = 3,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", EnhancementIcon, Enhancement) end,
            args = {
            }
        },
        Restoration = {
            order = 4,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", RestorationIcon, Restoration) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end