---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 7
ShamanSpells = {

}

ElementalSpells = {

}

EnhancementSpells = {

}

RestorationSpells = {

}

ShamanPVPSpells = {

}

ShamanLegendary = {
}

function insertShamanConfig(configRoot)
    local _,Elemental,_,ElementalIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Enhancement,_,EnhancementIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Restoration,_,RestorationIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Shaman = {
            order = 1,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", "Interface\\ICONS\\Classicon_Shaman", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Elemental = {
            order = 2,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", ElementalIcon, Elemental) end,
            args = {
            }
        },
        Enhancement = {
            order = 3,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", EnhancementIcon, Enhancement) end,
            args = {
            }
        },
        Restoration = {
            order = 4,
            type = "group",
            name = function() return format("|cff0070DE|T%s:16|t %s", RestorationIcon, Restoration) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        Legendary= {
            order = 6,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
            args = {
            }
        },
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
    }


end