---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:46
---


local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 9
WarlockSpells = {
    104773,     --心志堅定
    48018,      --惡魔法陣
    333889,     --惡魔支配
    5697,       --魔息術
    108416,     --黑暗契約
    196099,     --犧牲魔典
}

AfflictionSpells = {
    113860,     --黑暗之魂:悲慘
}

DemonologySpells = {
    205146,     --惡魔呼喚
    264173,     --魔能之核
}

DestructionSpells = {
    113858,     --黑暗之魂:易變
    117828,     --爆燃
    266030,     --逆轉熵值
}

WarlockPVPSpells = {

}

WarlockLegendary = {
}

function insertWarlockConfig(configRoot)
    local _,Affliction,_,AfflictionIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Demonology,_,DemonologyIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Destruction,_,DestructionIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Warlock = {
            order = 1,
            type = "group",
            name = function() return format("|cff9482C9|T%s:16|t %s", "Interface\\ICONS\\Classicon_Warlock", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Affliction = {
            order = 2,
            type = "group",
            name = function() return format("|cff9482C9|T%s:16|t %s", AfflictionIcon, Affliction) end,
            args = {
            }
        },
        Demonology = {
            order = 3,
            type = "group",
            name = function() return format("|cff9482C9|T%s:16|t %s", DemonologyIcon, Demonology) end,
            args = {
            }
        },
        Destruction = {
            order = 4,
            type = "group",
            name = function() return format("|cff9482C9|T%s:16|t %s", DestructionIcon, Destruction) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end