---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/5/15 上午 02:45
---

local L = LibStub("AceLocale-3.0"):GetLocale("PersonalBuff")

local ClassID = 1
WarriorSpells = {
    107574,     --巨象化身
    132404,     --盾牌格檔
    190456,     --無視苦痛
    97463,      --振奮咆哮
    18499,      --狂暴之怒
    32216,      --勝利衝擊
    23920,      --法術反射
}

ArmsSpells = {
    118038,     --劍下亡魂
    7384,       --壓制
    260708,     --橫掃攻擊
}

FurySpells = {
    1719,       --魯莽
    184362,     --狂怒
    184364,     --狂怒恢復
    275672,     --粉碎怒擊
    335082,     --狂亂
    248622,     --趕盡殺絕
}

WarriorProtectionSpells = {
    871,        --盾牆
    12975,      --破釜沉舟
}

WarriorPVPSpells = {

}

WarriorLegendary = {
}

function insertWarriorConfig(configRoot)
    local _,Arms,_,ArmsIcon = GetSpecializationInfoForClassID(ClassID, 1)
    local _,Fury,_,FuryIcon = GetSpecializationInfoForClassID(ClassID, 2)
    local _,Protection,_,ProtectionIcon = GetSpecializationInfoForClassID(ClassID, 3)

    configRoot.args.BuffOption.args = {
        Warrior = {
            order = 1,
            type = "group",
            name = function() return format("|cffC79C6E|T%s:16|t %s", "Interface\\ICONS\\Classicon_Warrior", GetClassInfo(ClassID)) end,
            args = {
            }
        },
        Arms = {
            order = 2,
            type = "group",
            name = function() return format("|cffC79C6E|T%s:16|t %s", ArmsIcon, Arms) end,
            args = {
            }
        },
        Fury = {
            order = 3,
            type = "group",
            name = function() return format("|cffC79C6E|T%s:16|t %s", FuryIcon, Fury) end,
            args = {
            }
        },
        Protection = {
            order = 4,
            type = "group",
            name = function() return format("|cffC79C6E|T%s:16|t %s", ProtectionIcon, Protection) end,
            args = {
            }
        },
        PVP = {
            order = 5,
            type = "group",
            name = function() return format("|cff8A2BE2|T%s:16|t %s", "Interface\\ICONS\\ability_pvp_gladiatormedallion", "PVP") end,
            args = {
            }
        },
        --Legendary= {
        --    order = 6,
        --    type = "group",
        --    name = function() return format("|cffFF8000|T%s:16|t %s", "Interface\\ICONS\\inv_antorus_turquoise", L["Legendary"]) end,
        --    args = {
        --    }
        --},
        Bloodlust= {
            order = 7,
            type = "group",
            name = function() return format("|cffFF8000|T%s:16|t %s", GetSpellTexture(2825), GetSpellInfo(2825)) end,
            args = {
            }
        },
        Common = {
            order = 8,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["Common"]) end,
            args = {}
        },
        Custom = {
            order = 9,
            type = "group",
            name = function() return format("|T%s:16|t %s", "Interface\\ICONS\\Trade_engineering", L["custom"]) end,
            args = {}
        },
    }


end