
local L = LibStub("AceLocale-3.0"):NewLocale("PlateEnhancement", "enUS", true)
L["Plate Enhancement"] = "Plate Enhancement"
L["General Settings"] = "General Settings"
L["Buffs"] = "Buffs"
L["author"] = "author"
L["Debuffs"] = "Debuffs"
L["icons"] = "Icons"
L["option"] = "Option"
L["iconSize"] = "Icon size"
L["fontSize"] = "Font size"
L["iconSpacing"] = "Icon spacing"
L["font"] = "font"
L["general"] = "general"
L["X offset"] = "X offset"
L["Y offset"] = "Y offset"
L["count font"] = "count font"
L["count font size"] = "count font size"