---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2021/1/29 下午 08:38
---
local media = LibStub("LibSharedMedia-3.0")

healthFrame = nil
powerFrame = nil

local function updatePlayerHealth()
    local playerHealth = UnitHealth("player")
    healthFrame.text:SetText(playerHealth)
end

local function updatePlayerPower()
    local playerPower = UnitPower("player")
    powerFrame.text:SetText(playerPower)
end

function InitializeHealthNumber(width,height)
    healthFrame = CreateFrame("Frame",nil,nil)
    healthFrame:SetSize(width, height)

    local healthTexture = healthFrame:CreateTexture(nil,"ARTWORK")
    healthTexture:SetTexture(0,0,0,0)

    local healthText = healthFrame:CreateFontString(nil, "OVERLAY")
    healthText:SetFont(media.MediaTable.font[aceDB.char.resourceFont], aceDB.char.resourceFontSize, "OUTLINE")
    healthText:SetPoint(aceDB.char.resourceAlignment, 0, 0)
    healthFrame.text = healthText

    healthFrame.update = updatePlayerHealth
end

function InitializePowerNumber(width,height)
    powerFrame = CreateFrame("Frame",nil,nil)
    powerFrame:SetSize(width, height)

    local powerTexture = powerFrame:CreateTexture(nil,"ARTWORK")
    powerTexture:SetTexture(0,0,0,0)

    local powerText = powerFrame:CreateFontString(nil, "OVERLAY")
    powerText:SetFont(media.MediaTable.font[aceDB.char.resourceFont], aceDB.char.resourceFontSize, "OUTLINE")
    powerText:SetPoint(aceDB.char.resourceAlignment, 0, 0)
    powerFrame.text = powerText

    powerFrame.update = updatePlayerPower
end
