---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2020/10/31 下午 03:11
---
local L = LibStub("AceLocale-3.0"):NewLocale("PlateEnhancement", "zhTW")
L["Plate Enhancement"] = "血條增強"
L["General Settings"] = "一般設定"
L["Player auras"] = "玩家增益"
L["author"] = "作者"