---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kira1101.
--- DateTime: 2020/10/31 下午 03:11
---
local L = LibStub("AceLocale-3.0"):NewLocale("PlateEnhancement", "zhTW")
L["Plate Enhancement"] = "血條增強"
L["General Settings"] = "一般設定"
L["Buffs"] = "增益"
L["author"] = "作者"
L["Debuffs"] = "減益"
L["icons"] = "圖示"
L["option"] = "選項"
L["iconSize"] = "圖示大小"
L["fontSize"] = "字體大小"
L["iconSpacing"] = "圖示間隔"
L["font"] = "字形"
L["general"] = "一般"
L["X offset"] = "水平位移"
L["Y offset"] = "垂直位移"
L["count font"] = "堆疊字形"
L["count font size"] = "堆疊字形大小"